// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Debug: print env values in development to help diagnose network issues (will appear in browser console)
if (import.meta.env.DEV) {
  // eslint-disable-next-line no-console
  console.log('DEBUG_SUPABASE_URL=', SUPABASE_URL);
  // eslint-disable-next-line no-console
  console.log('DEBUG_SUPABASE_KEY=', SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing');
}