// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function normalizeSupabaseUrl(url: string | undefined) {
  const trimmedUrl = url?.trim();

  if (!trimmedUrl) {
    throw new Error('Missing VITE_SUPABASE_URL. Add it to .env and restart the Vite dev server.');
  }

  if (!/^https:\/\/.+\.supabase\.co\/?$/.test(trimmedUrl)) {
    throw new Error(
      `Invalid VITE_SUPABASE_URL: "${trimmedUrl}". Expected format: https://your-project-ref.supabase.co`
    );
  }

  return trimmedUrl.replace(/\/+$/, '');
}

const SUPABASE_URL = normalizeSupabaseUrl(rawSupabaseUrl);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Debug: print env values in development to help diagnose network issues (will appear in browser console)
if (import.meta.env.DEV) {
  // eslint-disable-next-line no-console
  console.log('DEBUG_SUPABASE_URL=', SUPABASE_URL);
  // eslint-disable-next-line no-console
  console.log('DEBUG_SUPABASE_KEY=', SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing');
}
